# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

- task: katalonTask@0
  inputs:
    version: '7.6.6'
    executeArgs: 'katalon -propertiesFile = "C:\Users\Erick\Downloads\CrearTicket\CrearTicket\console.properties" -runMode = console'